version: 2
jobs:
  build:
    docker:
      - image: fr3akyphantom/pitchblack-builder:latest
    environment:
      MANIFEST_BRANCH: 'twrp-6.0'
      PBRP_BRANCH: 'android-9.0'
      VERSION: '2.9.0'
      VENDOR: 'mmx'
      CODENAME: 's310'
      BUILD_LUNCH: 'omni_s310-userdebug'
      TEST_BUILD: 'true'
    working_directory: /home/builder/pitchblack
    steps:
      - checkout
      - run:
          name: AIO Build
          command: |
            sudo apt-get install -y tar
            echo "Set GitAuth Infos too"
            git config --global user.email $GitHubMail
            git config --global user.name $GitHubName
            git config --global color.ui true
            export TEST_BUILD=true
            wget -q https://raw.githubusercontent.com/PitchBlackRecoveryProject/vendor_pb/pb/build.sh
            source build.sh ${SFUserName} ${SFPassword} ${GITHUB_TOKEN}
workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          context: org-global
